# Installing PyTorch

Get installation command for you configuration here: https://pytorch.org/

# Verifying the install

In [1]:
import torch

In [2]:
print(torch.__version__)

2.0.1+cu117


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'11.7'

# Using CUDA

In [5]:
t = torch.tensor([1, 2, 3])
t

tensor([1, 2, 3])

In [6]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

# Tensors Explained - Data Structures of Deep Learning

multi-dimention array, nd-array, nd-tensor

## Indexes

In [7]:
a = [1, 2, 3 ,4]
a[2]

3

In [8]:
dd = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
dd[0][2]

3

## Rank

In [9]:
dd[0], dd[1], dd[2]

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [10]:
dd[0][0], dd[1][0], dd[2][0]

(1, 4, 7)

## Shape

In [11]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
type(t)

torch.Tensor

In [13]:
t.shape

torch.Size([3, 3])

In [14]:
t.reshape(1, 9).shape

torch.Size([1, 9])

# PyTorch Tensors Explained - Neural Network Programming

In [15]:
import torch
import numpy as np

## Tensor class

Tensors in PyTorch are represented using the <code>torch.Tensor</code> class

In [16]:
t = torch.Tensor()
type(t)

torch.Tensor

## Tensor attributes

In [17]:
t.dtype, t.device, t.layout

(torch.float32, device(type='cpu'), torch.strided)

In [18]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

Tensor computations depend on the device and the type.

In [20]:
t1, t2 = torch.tensor([1, 2, 3]), torch.tensor([1., 2., 3.])
t3 = t1.cuda()
t1.dtype, t2.dtype, t3.dtype

(torch.int64, torch.float32, torch.int64)

## Creation options using data

In [21]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [22]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [23]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

## Creation options without data

In [26]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [27]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [28]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [29]:
torch.rand(2, 2)

tensor([[0.1370, 0.4807],
        [0.2083, 0.5305]])

# Creating PyTorch Tensors - Best Options

In [30]:
import torch
import numpy as np

In [31]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [37]:
'''
Constructor (w/o functionality of dtype) vs Factory (preferred, type inferrence, flexible & extensionable)
Tensor & tensor copy memory, while as_tensor & from_numpy share memory
Best Option: torch.tensor() > torch.as_tensor()
'''
t1, t2, t3, t4, t5 = torch.Tensor(data), torch.tensor(data), torch.as_tensor(data), torch.from_numpy(data), torch.tensor(data, dtype=torch.float64)
t1, t2, t3, t4, t5, torch.get_default_dtype()

(tensor([1., 2., 3.]),
 tensor([1, 2, 3], dtype=torch.int32),
 tensor([1, 2, 3], dtype=torch.int32),
 tensor([1, 2, 3], dtype=torch.int32),
 tensor([1., 2., 3.], dtype=torch.float64),
 torch.float32)

# Reshaping Explained - PyTorch Tensors for Deep Learning

In [40]:
import torch

In [46]:
t = torch.tensor(
    [
        [1,1,1,1],
        [2,2,2,2],
        [3,3,3,3]
    ], dtype=torch.float32
)
t.size(), t.shape, len(t.shape), torch.tensor(t.shape).prod(), t.numel()

(torch.Size([3, 4]), torch.Size([3, 4]), 2, tensor(12), 12)

In [56]:
t.reshape(1,12).shape, t.reshape(1,-1).squeeze().shape, t.reshape(1,-1).squeeze().unsqueeze(dim=0).shape, t.flatten()

(torch.Size([1, 12]),
 torch.Size([12]),
 torch.Size([1, 12]),
 tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]))

In [57]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

# CNN Flatten Operation Visualized - Tensor Batch Processing for Deep Learning

In [58]:
import torch

In [63]:
t1, t2, t3 = torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]]), torch.tensor([[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2]]), torch.tensor([[3,3,3,3],[3,3,3,3],[3,3,3,3],[3,3,3,3]])
torch.stack((t1, t2, t3)).reshape(3,1,4,4).flatten(start_dim=0)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

# Tensors for Deep Learning - Broadcasting and Element-wise Operations

In [64]:
import torch
import numpy as np

In [65]:
''' Same shape, Broadcasting (low -> high, np.broadcast_to(input, shape)) '''
t1, t2 = torch.tensor([[1,2], [3,4]], dtype=torch.float32), torch.tensor([[9,8], [7,6]], dtype=torch.float32)
t3, t4 = t1 + t2, t1 + 2

# ArgMax and Reduction Ops - Tensors for Deep Learning

In [66]:
import torch
import numpy as np

In [68]:
t = torch.tensor([[0,1,0], [2,0,2], [0,3,0]], dtype=torch.float32)
t.sum(), t.prod(), t.mean(), t.std()

(tensor(8.), tensor(0.), tensor(0.8889), tensor(1.1667))

In [70]:
''' ArgMax: index of the max value '''
t = torch.tensor([[1,0,0,2], [0,3,3,0], [4,0,0,5]], dtype=torch.float32)
t.max(), t.argmax(), t.max(dim=0)

(tensor(5.),
 tensor(11),
 torch.return_types.max(
 values=tensor([4., 3., 3., 5.]),
 indices=tensor([2, 1, 1, 2])))